services:
  api:
    build: .
    container_name: deepclaude_api
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./config.toml:/usr/local/bin/config.toml:ro
    environment:
      - RUST_LOG=info
    networks:
      - deepclaude_network
    env_file: .env

networks:
  deepclaude_network:
    name: deepclaude_network
